### ISSUE TITLE
Absturzt, Grafikfehler und mehr

### ISSUE THREAD

**Issue by Spielemaxe** [MontyTRC89/TombEngine#1364]
Startet man ein Neues Projekt und nimmt die Tomb Engine (BETA) Funktioniert so Halbwegs alles.
Startet man allerdings ein Projekt und Nimmt die Next Gen und will dann das Level Testen Pfeifft der Editor mit der Meldung es würde Failed to Seput Direct X fehlen ????
Wie kann das Fehlen und bei der TB Engine nicht ????? Geister Code ?
Aber das ist nicht das einzige, auch Verschwindet des Öfteren unten Links die Option zum Hinzufügen der wad datei dann  ist auf einmal ein anderes Menü da mit dem man nichts Anfangen kann.
Beim Compilieren wird ein Gelber Text Angezeigt, aber Anstatt das Compilen Stoppt damit man den Lesen kann und den Fehler beheben kann wird weiter Compiliert NUR damit es dann zum Absturz führt und zum EDITOR zurück geht, wie Intelligent.
Sorry, aber der Editor ist immer noch so Verbugt wie vor Jahren und es wird sich darum nicht Gekümmert, lieber wird neues Eingefügt wie die Notes, die auch total Verbugt sind.
Sorry, mit dem Editor kann man NICHT Vernünftig Arbeiten.
Und nebenbei, wo sind eigentlich die Video Tutorials wie Angekündigt damals in den Youtube Videos ???????
Nur Bla Bla und das war es.

**Comment by Lwmte** [comment]
No constructive feedback.

**Comment by Spielemaxe** [comment]
Was heisst hier Kein konstruktives Feedback ?????
Ach der Herr möchte es nicht das man sich Beschwert oder was ? Ich glaub es hakt. Mach dein Krempel Richtig dann braucht sich auch keiner zu Beschweren und mach hier nicht ein auf Großkotzig.

**Comment by Joey79100** [comment]
You seem to have a few issues *using* the editor.

You could have asked kindly for a little help, to find the reasons behind your issues, that would be more helpful and people would have been happy to help. There are multiple places (Discord servers, Facebook groups, Tomb Raider Forums) in which you can ask for help to troubleshoot your issues. Fellow level builders (such as myself) are always happy to help others get into it.

Instead, you chose to straight up jump to the conclusion that the editor is the problem, seemingly without even thinking the problem might be somewhere else, and chose to give up and rant. This is quite a strange attitude, and you won't ever fix any issue if this is how you react to any of them.
Opening an issue on Github - whether it's for Tomb Editor or not - is made to raise an actual problem about the software, not for rants.

For instance:
- TRNG was made by Paolone way before Tomb Editor even existed: it was just shipped in so you could easily create a game for it, but the Tomb Editor developers have absolutely nothing to do with it or its possible issues.
- But even then, your DirectX issue is because you need to run the game's setup at least once (and select Hardware mode, and a resolution), this is inherited from the original tomb4.exe from 1999: not Paolone, not Tomb Editor devs, but Core Design.
- Warnings are also not errors, they warn you about something that *could* potentially cause issues, but also may not (and most of the time, they do not). Errors are red, and stop the compilation. Warnings are "skipped" for the only reason that you pressed the "Build _and play_" button, which, as you could expect from its name, will build the level and run the game so you can play without waiting. If you press the "Build" button that is just next to it, then the window is not closed.
- This is the TombEngine repository, which has nothing to do with TRNG, so even if Issues were a place for rants, it wouldn't even be the correct one.
