### ISSUE TITLE
Lever switch bug by ShadowXJaw

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/TombEngine#737]
Shadow (user) had a problem with the switch whereupon placing a pushable on the map, regardless of whether Lara interacted with it or not, Lara would not be able to reach the switch (constantly walking into the switch and never aligning herself).

**Comment by ShadowXJaw724** [comment]
This issue was more accurately caused by a PUSHABLE having animations in their ANIMATIONS.

Pushable Objects in TR4+ did not use animations, instead being controlled through code, and thus the bug happens like this:
Because of the animation, TEN becomes confused (most likely does the same in TR4 / TRNG), and that correlates to Lara's inability to correctly align herself to switches, levers, or any trigger objects. ( Trigger objects, which are objects Lara can use to trigger a SWITCH legacy trigger. ) 

A simple fix to the issue would be to remove all of the animations and correct the state of a PUSHABLE.
