### ISSUE TITLE
Switches OCB 5 valve wheel needs to be used twice to activate trigger

### ISSUE THREAD

**Issue by diebasis72** [MontyTRC89/TombEngine#776]
When using the new OCB value 5 for valve wheel, you have to use it twice to activate a trigger e.g. open a door.

Trigger set on the ground in front of the switch are normal "Switch for Switch" and "Trigger for door" trigger.

![Unbenannt 2](https://user-images.githubusercontent.com/58602705/195804604-73bcfb1d-1bc2-41ae-a3a9-86c732bbae41.jpg)

Also using the valve wheel again, doesn't close the door, but I guess that's normal TR3 behaviour.

See here:

https://streamable.com/wuik3m

**Comment by Lwmte** [comment]
I think this is an asset issue because of inverted state IDs for valve switch.

**Comment by goldlife2904** [comment]
Once the user "Not_again" gave instructions on how to correct the state ID of the Tr2 or Tr3 switches. Die Basis did that. That's why you can also find the corrected switches from DieBasis on "trlevel.de".
In TEN there was added OCB and then somehow managed that you can just take the "uncorrected ones" with the wrong State IDs from the TR3 parts. That's why DieBasis corrected ones have become superfluous.

Up to version 1.0.1 of TEN you couldn't take the "Small Push Button" and the "Small Lever Switch" easily, because there were no OCB entries. Die Basis wrote some Lua code to play certain animations to get this these switches to work - but this only worked with his fixed ones (as described above), so you could turn them "ON" and "OFF".
His Lua script was then superfluous - because there were added OCB entries for the switches (in version 1.0.2) . Here is the TEN entry for this:

TEN version 1.02.:

Added new switch OCBs:
- 0 for wall switch
- 1 for small wall switch
- 2 for small buttons
- 3 for big buttons
- 4 for giant button (sequence switch)
- 5 for valve turn
- 6 for hole switch
- any other OCBs play corresponding switch on anim or OCB+1 switch off anim.

However, in TEN that is somehow managed to get OCB codes to work with those from the original TR3 parts, including the "ON" and "OFF".

Since TEN OCB entries, DieBasis fixed ones don't work anylonger and builders has to be forced to take the broken ones.

**Comment by Adngel** [comment]
It wasn't the asset, it was the function that manages the switch triggers that for a reason that I unknown, was negating the validation of the switch if this one has OCB 5 or OCB 6.

I think those may have been used for heavy triggers destinated to the enemies.

In any case, fix is already on the way. (I just want to polish other interactive objects that also are buggy).
