### ISSUE TITLE
Look button + Crouch issue

### ISSUE THREAD

**Issue by Mrshina** [MontyTRC89/TombEngine#796]
You can't use left arrow to look around while in crouch.

**Comment by Lwmte** [comment]
Is it another keyboard-related issue (hardware or OIS)? Does it happen in original games?

**Comment by Mrshina** [comment]
Oh, it might be. I tried on another pc and it works. Doesn't happen in original games.

**Comment by Sezzary** [comment]
I have a similar problem with my laptop keyboard where certain combinations of keys will lock out other keys. It's very strange, but it might just be our hardware isn't made for gaming...

**Comment by Adngel** [comment]
I can't replicate this error. It looks like may be more a hardware drivers issue more than problem in the code. (Or maybe has been fixed with the recent look camera changes).

In any case  is an old bug, not replicable and with no extra info, I'm going to close it. Please if the bug reappears, feel free to reopen this one or create a new one with the new info.
