### ISSUE TITLE
No flare hand up when operating certain switches

### ISSUE THREAD

**Issue by GeckoKid-JW** [MontyTRC89/TombEngine#823]
In OG games lara would operate underwater and jump switches with her flare hand in idle position and it just looks extremely wrong especially on jumpswitches.

**Comment by Adngel** [comment]
Added animation exclussion for flare pose for the next animations in lara_fire.cpp

- LA_WATERLEVER_PULL,
- LA_BUTTON_GIANT_PUSH,
- LA_BUTTON_LARGE_PUSH,
- LA_JUMPSWITCH_PULL,
- LA_UNDERWATER_CEILING_SWITCH_PULL,
- LA_VALVE_TURN

If more animations require both hands instead of flare pose, please report to us.
