### ISSUE TITLE
Pushable item losts its collision if pushed more than once

### ISSUE THREAD

**Issue by WalrusTR** [MontyTRC89/TombEngine#886]
Apparently it happens only when the pushable is moved above and over a closed trapdoor. If the pushable is pushed more than once, it losts its collision and starts to disappear from camera. Pushed or pulled just once, don't cause the issue. Attached there are project+wad+textures.

How to repro:
Make Lara push the item a couple of time without releasing Action key

[TenTest.zip](https://github.com/MontyTRC89/TombEngine/files/10141292/TenTest.zip)

**Comment by Adngel** [comment]
After an initial refactor of the pushables stack system, the problem with the pushable room change was solved (The wrong room change is what was causing the pushable to loose its properties). 

However the problem still persists on Lara when she is pulling from the pushable through several trapdoors. I suspect the error may have a similar nature, but surelly in some place of Lara code, no in the pushable code.

**Comment by Adngel** [comment]
This issue is about the old pushable system. 

In the remake system, I don't perceive this issue. 

Notice that the new remake system, there are two pushables tipes. 
- The normal ones use the common mesh object collision.
- The climbable ones use the bridge collision, this one was the one that cause the problem described by Walrus.

In the remake method, it deactivates the bridge collision while these are being moved, and reactivate them when the movement has ended. That reduced many problems like for example, when the climbable pushables were being moved over trapdoors (that also used bridge collision).

Also, the remake method have changed the Lara's collision function while she is in pushable pulling/pushing states, now Lara won't collide with objects while is doing thise movement (including the collision with the own pushable). The bug this caused was happening in random moments, but with this method, problems like the described in this issue neither should keep happening.


So at the moment I'll close this one, if another new issue appear (or reappear in the remake pushable system), please open a new issue with the updated data.
