### ISSUE TITLE
Feature request: File manipulation via Lua

### ISSUE THREAD

**Issue by Kubsy** [MontyTRC89/TombEngine#928]
It was discussed a while ago and it was kind of "rejected" however I see this as a useful feature:

In recent TRLE levels that I played, the gameplay consisted of fetch quests like: "I need X to open Y", "Oh no X person wants Y but I need Z in order to get Y" which is pretty annoying because:

1) you can forget easily about what to do.
2) only appears **once** (as I have seen in almost all TRLE levels) and you cannot repeat the text.

So I think that being able to manipulate .txt files would be great and this is one of the many scenarios i could think of that file manipulation would be useful because the builder might be able to create a script where the scripts parses the .txt file whenever lara interacts with a book for example to get current objectives and prints on the screen.

File manipulation would look like this:
- Be able to create, save, write, read .txt files.
- Save text files in the Scripts folder. 
- Clear the text files if the user starts a new game.

I think this feature is similar to ImportFile= in TRNG however don't take that for granted because I don't know how to use it + it was not used often (or almost never) by builders so there's lack of documentation for that command.

or this stuff would be all converted into a diary feature where you write text into a diary and remove it dynamically.

We can further discuss this on github.

**Comment by hispidence** [comment]
I'm extremely hesitant to open Pandora's box here, even just a little bit, because of the security implications of letting level scripts modify files on someone's system. I know there are ways around it to do it safely, but it's still something we shouldn't consider unless there's a very good reason for it.

For the feature you've mentioned, just using a var called `GameVars.diary`, and using that to store any of the text you want, will serve the same purposes (will be automatically saved and loaded with saved games and cleared on a new game), and actually would be cleaner and more efficient than loading in a text file.
